<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="LAPTOP-6I0EBU3A" failures="1" tests="1" name="Default test" time="11.161" errors="0" timestamp="2023-09-23T18:32:13 EDT">
  <testcase classname="testCases.LogIn" name="verifyLoginWithValidEmailInvalidPassward" time="0.947">
    <failure type="java.lang.AssertionError" message="Expected waring message is not displayed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Expected waring message is not displayed expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at testCases.LogIn.verifyLoginWithValidEmailInvalidPassward(LogIn.java:105)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyLoginWithValidEmailInvalidPassward -->
  <testcase classname="testCases.LogIn" name="verifyLoginWithInvalidCradentials" time="0.0">
    <ignored/>
  </testcase> <!-- verifyLoginWithInvalidCradentials -->
  <testcase classname="testCases.LogIn" name="verifyLoginWithInvalidEmailValidPassward" time="0.0">
    <ignored/>
  </testcase> <!-- verifyLoginWithInvalidEmailValidPassward -->
  <testcase classname="testCases.LogIn" name="verifyLoinWithValidCradentials" time="0.0">
    <ignored/>
  </testcase> <!-- verifyLoinWithValidCradentials -->
  <testcase classname="testCases.LogIn" name="verifyLoginWithoutCradentials" time="0.0">
    <ignored/>
  </testcase> <!-- verifyLoginWithoutCradentials -->
</testsuite> <!-- Default test -->
